@base_url = 192.168.1.158
@port = 8080

@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTYzNjkwMzU4OCwianRpIjoiNWNmNTdjZjQtYWYyZS00MDFkLTk5MjEtODFhZWM4OTk3NDFlIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6ImFkbWluIiwibmJmIjoxNjM2OTAzNTg4LCJleHAiOjE2MzY5MTc5ODgsInJvbGVzIjpbIkFETUlOIl19.Ul1rzYGZKPFZ8tzN6XTxQGLYsf7HjKcfA-WTRMiwotY

@domainUUID = 0283447e-4e59-41e3-bc27-7a789c29882c

#
# Single Domaine
#

GET http://{{base_url}}:{{port}}/domain/{{domainUUID}}
Content-Type: application/json
Authorization: Bearer {{token}} 

DELETE http://{{base_url}}:{{port}}/domain/manage/{{domainUUID}}
Content-Type: application/json
Authorization: Bearer {{token}}