server: 
  host: 0.0.0.0
  port: 8080
  debug: false
  secret: ChangeThisSecret

working_dir: /data/heimdall  
database: 
  path: "/data/heimdall/db.json"

security:
  jwt_ttl_minutes: 240
  admin:
    username: admin
    password: password


